// GET POSTS
export const GET_POSTS_START = 'GET_POSTS_START'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR'

// GET POST
export const GET_POST_START = 'GET_POST_START'
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS'
export const GET_POST_ERROR = 'GET_POST_ERROR'

// GET CREATE
export const CREATE_POST_START = 'CREATE_POSTS_START'
export const CREATE_POST_SUCCESS = 'CREATE_POSTS_SUCCESS'
export const CREATE_POST_ERROR = 'CREATE_POSTS_ERROR'

// GET UPDATE
export const UPDATE_POST_START = 'UPDATE_POSTS_START'
export const UPDATE_POST_SUCCESS = 'UPDATE_POSTS_SUCCESS'
export const UPDATE_POST_ERROR = 'UPDATE_POSTS_ERROR'

// GET DELETE
export const DELETE_POST_START = 'DELETE_POSTS_START'
export const DELETE_POST_SUCCESS = 'DELETE_POSTS_SUCCESS'
export const DELETE_POST_ERROR = 'DELETE_POSTS_ERROR'
